import 'package:avtoskola_varketilshi/Models/subcategory_model.dart';

class SubCategoryService {
  static List<SubCategoryModel> getSubCategories(String category) {
    // All 32 sub-categories for each vehicle category
    final List<SubCategoryModel> allSubCategories = [
      SubCategoryModel(
        id: 1,
        name: 'Traffic Rules',
        nameEn: 'Traffic Rules',
        nameKa: 'საგზაო მოძრაობის წესები',
        description: 'Basic traffic rules and regulations',
        descriptionEn: 'Basic traffic rules and regulations',
        descriptionKa: 'საგზაო მოძრაობის ძირითადი წესები და რეგულაციები',
        questionCount: 45,
        iconPath: 'assets/icons/traffic_rules.png',
        category: category,
      ),
      SubCategoryModel(
        id: 2,
        name: 'Road Signs',
        nameEn: 'Road Signs',
        nameKa: 'საგზაო ნიშნები',
        description: 'All types of road signs',
        descriptionEn: 'All types of road signs',
        descriptionKa: 'ყველა ტიპის საგზაო ნიშნები',
        questionCount: 38,
        iconPath: 'assets/icons/road_signs.png',
        category: category,
      ),
      SubCategoryModel(
        id: 3,
        name: 'Warning Signs',
        nameEn: 'Warning Signs',
        nameKa: 'გამაფრთხილებელი ნიშნები',
        description: 'Warning and caution signs',
        descriptionEn: 'Warning and caution signs',
        descriptionKa: 'გამაფრთხილებელი და სიფრთხილის ნიშნები',
        questionCount: 32,
        iconPath: 'assets/icons/warning_signs.png',
        category: category,
      ),
      SubCategoryModel(
        id: 4,
        name: 'Priority Signs',
        nameEn: 'Priority Signs',
        nameKa: 'პრიორიტეტის ნიშნები',
        description: 'Right of way and priority signs',
        descriptionEn: 'Right of way and priority signs',
        descriptionKa: 'გზის უფლების და პრიორიტეტის ნიშნები',
        questionCount: 28,
        iconPath: 'assets/icons/priority_signs.png',
        category: category,
      ),
      SubCategoryModel(
        id: 5,
        name: 'Prohibition Signs',
        nameEn: 'Prohibition Signs',
        nameKa: 'ამკრძალავი ნიშნები',
        description: 'Prohibition and restriction signs',
        descriptionEn: 'Prohibition and restriction signs',
        descriptionKa: 'აკრძალვის და შეზღუდვის ნიშნები',
        questionCount: 35,
        iconPath: 'assets/icons/prohibition_signs.png',
        category: category,
      ),
      SubCategoryModel(
        id: 6,
        name: 'Mandatory Signs',
        nameEn: 'Mandatory Signs',
        nameKa: 'სავალდებულო ნიშნები',
        description: 'Mandatory instruction signs',
        descriptionEn: 'Mandatory instruction signs',
        descriptionKa: 'სავალდებულო ინსტრუქციის ნიშნები',
        questionCount: 30,
        iconPath: 'assets/icons/mandatory_signs.png',
        category: category,
      ),
      SubCategoryModel(
        id: 7,
        name: 'Information Signs',
        nameEn: 'Information Signs',
        nameKa: 'საინფორმაციო ნიშნები',
        description: 'Informational and guidance signs',
        descriptionEn: 'Informational and guidance signs',
        descriptionKa: 'საინფორმაციო და სახელმძღვანელო ნიშნები',
        questionCount: 42,
        iconPath: 'assets/icons/info_signs.png',
        category: category,
      ),
      SubCategoryModel(
        id: 8,
        name: 'Road Markings',
        nameEn: 'Road Markings',
        nameKa: 'საგზაო მონიშვნები',
        description: 'Road surface markings and lines',
        descriptionEn: 'Road surface markings and lines',
        descriptionKa: 'გზის საფარის მონიშვნები და ხაზები',
        questionCount: 25,
        iconPath: 'assets/icons/road_markings.png',
        category: category,
      ),
      SubCategoryModel(
        id: 9,
        name: 'Traffic Lights',
        nameEn: 'Traffic Lights',
        nameKa: 'შუქნიშნები',
        description: 'Traffic light signals and rules',
        descriptionEn: 'Traffic light signals and rules',
        descriptionKa: 'შუქნიშნის სიგნალები და წესები',
        questionCount: 20,
        iconPath: 'assets/icons/traffic_lights.png',
        category: category,
      ),
      SubCategoryModel(
        id: 10,
        name: 'Intersections',
        nameEn: 'Intersections',
        nameKa: 'გზაჯვარედინები',
        description: 'Intersection rules and navigation',
        descriptionEn: 'Intersection rules and navigation',
        descriptionKa: 'გზაჯვარედინის წესები და ნავიგაცია',
        questionCount: 36,
        iconPath: 'assets/icons/intersections.png',
        category: category,
      ),
      SubCategoryModel(
        id: 11,
        name: 'Overtaking',
        nameEn: 'Overtaking',
        nameKa: 'გასწრება',
        description: 'Overtaking rules and safety',
        descriptionEn: 'Overtaking rules and safety',
        descriptionKa: 'გასწრების წესები და უსაფრთხოება',
        questionCount: 28,
        iconPath: 'assets/icons/overtaking.png',
        category: category,
      ),
      SubCategoryModel(
        id: 12,
        name: 'Parking',
        nameEn: 'Parking',
        nameKa: 'პარკირება',
        description: 'Parking rules and regulations',
        descriptionEn: 'Parking rules and regulations',
        descriptionKa: 'პარკირების წესები და რეგულაციები',
        questionCount: 24,
        iconPath: 'assets/icons/parking.png',
        category: category,
      ),
      SubCategoryModel(
        id: 13,
        name: 'Speed Limits',
        nameEn: 'Speed Limits',
        nameKa: 'სიჩქარის შეზღუდვები',
        description: 'Speed limits and regulations',
        descriptionEn: 'Speed limits and regulations',
        descriptionKa: 'სიჩქარის ლიმიტები და რეგულაციები',
        questionCount: 22,
        iconPath: 'assets/icons/speed_limits.png',
        category: category,
      ),
      SubCategoryModel(
        id: 14,
        name: 'Safety Equipment',
        nameEn: 'Safety Equipment',
        nameKa: 'უსაფრთხოების აღჭურვილობა',
        description: 'Vehicle safety equipment requirements',
        descriptionEn: 'Vehicle safety equipment requirements',
        descriptionKa: 'ავტომობილის უსაფრთხოების აღჭურვილობის მოთხოვნები',
        questionCount: 18,
        iconPath: 'assets/icons/safety_equipment.png',
        category: category,
      ),
      SubCategoryModel(
        id: 15,
        name: 'Emergency Situations',
        nameEn: 'Emergency Situations',
        nameKa: 'საგანგებო სიტუაციები',
        description: 'Handling emergency situations',
        descriptionEn: 'Handling emergency situations',
        descriptionKa: 'საგანგებო სიტუაციების მართვა',
        questionCount: 26,
        iconPath: 'assets/icons/emergency.png',
        category: category,
      ),
      SubCategoryModel(
        id: 16,
        name: 'Weather Conditions',
        nameEn: 'Weather Conditions',
        nameKa: 'ამინდის პირობები',
        description: 'Driving in different weather conditions',
        descriptionEn: 'Driving in different weather conditions',
        descriptionKa: 'მართვა სხვადასხვა ამინდის პირობებში',
        questionCount: 20,
        iconPath: 'assets/icons/weather.png',
        category: category,
      ),
      SubCategoryModel(
        id: 17,
        name: 'Night Driving',
        nameEn: 'Night Driving',
        nameKa: 'ღამის მართვა',
        description: 'Night driving rules and safety',
        descriptionEn: 'Night driving rules and safety',
        descriptionKa: 'ღამით მართვის წესები და უსაფრთხოება',
        questionCount: 18,
        iconPath: 'assets/icons/night_driving.png',
        category: category,
      ),
      SubCategoryModel(
        id: 18,
        name: 'Pedestrian Crossings',
        nameEn: 'Pedestrian Crossings',
        nameKa: 'საფეხმავლო გადასასვლელები',
        description: 'Pedestrian crossing rules',
        descriptionEn: 'Pedestrian crossing rules',
        descriptionKa: 'საფეხმავლო გადასასვლელის წესები',
        questionCount: 22,
        iconPath: 'assets/icons/pedestrian.png',
        category: category,
      ),
      SubCategoryModel(
        id: 19,
        name: 'Roundabouts',
        nameEn: 'Roundabouts',
        nameKa: 'წრიული მოძრაობა',
        description: 'Roundabout navigation rules',
        descriptionEn: 'Roundabout navigation rules',
        descriptionKa: 'წრიული მოძრაობის წესები',
        questionCount: 16,
        iconPath: 'assets/icons/roundabout.png',
        category: category,
      ),
      SubCategoryModel(
        id: 20,
        name: 'Highway Driving',
        nameEn: 'Highway Driving',
        nameKa: 'ავტომაგისტრალზე მართვა',
        description: 'Highway and motorway rules',
        descriptionEn: 'Highway and motorway rules',
        descriptionKa: 'ავტომაგისტრალის და გზატკეცილის წესები',
        questionCount: 30,
        iconPath: 'assets/icons/highway.png',
        category: category,
      ),
      SubCategoryModel(
        id: 21,
        name: 'Vehicle Maintenance',
        nameEn: 'Vehicle Maintenance',
        nameKa: 'ავტომობილის მოვლა',
        description: 'Basic vehicle maintenance knowledge',
        descriptionEn: 'Basic vehicle maintenance knowledge',
        descriptionKa: 'ავტომობილის მოვლის ძირითადი ცოდნა',
        questionCount: 24,
        iconPath: 'assets/icons/maintenance.png',
        category: category,
      ),
      SubCategoryModel(
        id: 22,
        name: 'Documents',
        nameEn: 'Documents',
        nameKa: 'დოკუმენტები',
        description: 'Required documents and licenses',
        descriptionEn: 'Required documents and licenses',
        descriptionKa: 'საჭირო დოკუმენტები და ლიცენზიები',
        questionCount: 20,
        iconPath: 'assets/icons/documents.png',
        category: category,
      ),
      SubCategoryModel(
        id: 23,
        name: 'Insurance',
        nameEn: 'Insurance',
        nameKa: 'დაზღვევა',
        description: 'Vehicle insurance requirements',
        descriptionEn: 'Vehicle insurance requirements',
        descriptionKa: 'ავტომობილის დაზღვევის მოთხოვნები',
        questionCount: 15,
        iconPath: 'assets/icons/insurance.png',
        category: category,
      ),
      SubCategoryModel(
        id: 24,
        name: 'Alcohol & Drugs',
        nameEn: 'Alcohol & Drugs',
        nameKa: 'ალკოჰოლი და ნარკოტიკები',
        description: 'DUI laws and penalties',
        descriptionEn: 'DUI laws and penalties',
        descriptionKa: 'ნასვამ მდგომარეობაში მართვის კანონები და ჯარიმები',
        questionCount: 18,
        iconPath: 'assets/icons/alcohol.png',
        category: category,
      ),
      SubCategoryModel(
        id: 25,
        name: 'First Aid',
        nameEn: 'First Aid',
        nameKa: 'პირველადი დახმარება',
        description: 'Basic first aid knowledge',
        descriptionEn: 'Basic first aid knowledge',
        descriptionKa: 'პირველადი დახმარების ძირითადი ცოდნა',
        questionCount: 22,
        iconPath: 'assets/icons/first_aid.png',
        category: category,
      ),
      SubCategoryModel(
        id: 26,
        name: 'Eco Driving',
        nameEn: 'Eco Driving',
        nameKa: 'ეკო მართვა',
        description: 'Fuel-efficient driving techniques',
        descriptionEn: 'Fuel-efficient driving techniques',
        descriptionKa: 'საწვავის ეფექტური მართვის ტექნიკა',
        questionCount: 16,
        iconPath: 'assets/icons/eco_driving.png',
        category: category,
      ),
      SubCategoryModel(
        id: 27,
        name: 'Towing',
        nameEn: 'Towing',
        nameKa: 'ბუქსირება',
        description: 'Towing rules and regulations',
        descriptionEn: 'Towing rules and regulations',
        descriptionKa: 'ბუქსირების წესები და რეგულაციები',
        questionCount: 14,
        iconPath: 'assets/icons/towing.png',
        category: category,
      ),
      SubCategoryModel(
        id: 28,
        name: 'Loading & Cargo',
        nameEn: 'Loading & Cargo',
        nameKa: 'დატვირთვა და ტვირთი',
        description: 'Cargo loading and securing rules',
        descriptionEn: 'Cargo loading and securing rules',
        descriptionKa: 'ტვირთის დატვირთვის და დამაგრების წესები',
        questionCount: 20,
        iconPath: 'assets/icons/cargo.png',
        category: category,
      ),
      SubCategoryModel(
        id: 29,
        name: 'Passenger Safety',
        nameEn: 'Passenger Safety',
        nameKa: 'მგზავრის უსაფრთხოება',
        description: 'Passenger safety regulations',
        descriptionEn: 'Passenger safety regulations',
        descriptionKa: 'მგზავრის უსაფრთხოების რეგულაციები',
        questionCount: 18,
        iconPath: 'assets/icons/passenger.png',
        category: category,
      ),
      SubCategoryModel(
        id: 30,
        name: 'Bicycle & Motorcycle',
        nameEn: 'Bicycle & Motorcycle',
        nameKa: 'ველოსიპედი და მოტოციკლი',
        description: 'Sharing road with bicycles and motorcycles',
        descriptionEn: 'Sharing road with bicycles and motorcycles',
        descriptionKa: 'გზის გაზიარება ველოსიპედებთან და მოტოციკლებთან',
        questionCount: 16,
        iconPath: 'assets/icons/bicycle.png',
        category: category,
      ),
      SubCategoryModel(
        id: 31,
        name: 'Public Transport',
        nameEn: 'Public Transport',
        nameKa: 'საზოგადოებრივი ტრანსპორტი',
        description: 'Rules regarding public transport',
        descriptionEn: 'Rules regarding public transport',
        descriptionKa: 'საზოგადოებრივი ტრანსპორტის წესები',
        questionCount: 14,
        iconPath: 'assets/icons/bus.png',
        category: category,
      ),
      SubCategoryModel(
        id: 32,
        name: 'Special Vehicles',
        nameEn: 'Special Vehicles',
        nameKa: 'სპეციალური ტრანსპორტი',
        description: 'Emergency and special vehicle rules',
        descriptionEn: 'Emergency and special vehicle rules',
        descriptionKa: 'საგანგებო და სპეციალური ტრანსპორტის წესები',
        questionCount: 12,
        iconPath: 'assets/icons/special_vehicles.png',
        category: category,
      ),
    ];

    return allSubCategories;
  }
}
